### ISSUE TITLE
Dialog buttons overflow in low resolutions

### ISSUE THREAD

**Issue by J-Pabon** [equalitie/ouisync-app#122]
When the resolutio is low, the dialog buttons doesn’t scale down, causing the widget to overflow.

![Screenshot (Jun 29, 2022 21 55 39)](https://user-images.githubusercontent.com/13749449/176458040-eeaf534a-6ac1-4632-ab00-59e7afb6a8d8.png)

**Comment by inetic** [comment]
Should this be closed?

**Comment by J-Pabon** [comment]
Closed 5b4621e5951aaa969ae0a3a402f2cb91d0f04b99
