### ISSUE TITLE
Layout issue with the outdated app version indicator in the settings page

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#124]
![Screenshot_20220705-104854_OuiSync](https://user-images.githubusercontent.com/5271/177292997-300bc63e-ee75-406f-804d-1621ebc6ae76.png)

The indicator is pushed way to the right, making it barely visible. 

This is on a phone with screen size of 720 x 1280 pixels.

**Comment by inetic** [comment]
Fixed in e74506891dd94372523dac40ddbdca4fab1974bb
