### ISSUE TITLE
The notification icon shrinked to a single pixel

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#131]
![Screenshot_20220824-105330_OuiSync](https://user-images.githubusercontent.com/40127/186388098-3dcd2b0e-a186-41e8-b612-e72455a9e941.png)

**Comment by inetic** [comment]
Interestingly, this seem to happen only with the latest release apk. Not sure whether it's because one is release and the other is a debug build. Or whether building directly for the phone (`cargo run`) also executed some scripts to make this work.

**Comment by J-Pabon** [comment]
Closed ab9d966eacfe4002744c6283a7032e5bea2a848a
