### ISSUE TITLE
The "beta" tag not shown on launcher icon

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#132]
The beta tag is now on some of the icons in the `asset/` folder, but after installing the app it's not visible on the launcher icon

![Screenshot_20220824-115146_One UI Home](https://user-images.githubusercontent.com/40127/186388686-2ee5ff1e-8689-464a-af5b-914d5cc93b3b.jpg)
.

**Comment by J-Pabon** [comment]
Some versions of the old icon were still present.
All were removed and now the beta icon is used. 

Fixed: beta icon not present in release version. (f13d5a1296d5fe22b94cbed7f4749df275b01fe5)
Closes #132
