### ISSUE TITLE
Long file names are not fully shown (nor truncation is indicated)

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#138]
When a file with long name is created or uploaded into ouisync, it's name is not fully shown. I think we should:

1. if the name wouldn't fit, then try to use smaller font for that particular entry.
2. if the name still won't fit, then truncate it, but add "..." at the end to indicate that it's been truncated

Not sure whether flutter allows us to do the "if the name wouldn't fit" part.

Also, this issue is present in both the main browsing widget as well as in the "File details" bottom sheet.

**Comment by J-Pabon** [comment]
Closed here 44e92e66b461f1c87e820c43c0957be52f42dcc1
