### ISSUE TITLE
In the "File detail" bottom sheet, user is presented with options which may not be available

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#139]
For example, if the repository is in the "read" mode, clicking the "three dots" menu on a file (but please check directories as well) will open up options. In this "read" mode, the options "Rename", "Move" and "Delete" don't do anything (don't even show an error).

I think ideally we show the options as grayed out, and if the user tries to click on any of them we show a dialog explaining why that can't be done and perhaps also add a button that then shows another dialog for unlocking the repository in write mode.

**Comment by J-Pabon** [comment]
Closed here: 4f8f1cc823c05b80d7e78a1778bb53f6e1adcb66
