### ISSUE TITLE
No feedback when user forgets to select permissions in the sharing repo bottom sheet

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#142]
When I click to share a repository and I forget to select permission, then press the share button, nothing happens. It is expected that sharing shouldn't be done, but there should be some kind of feedback to let the user know that sharing can't proceed until a permission is selected.

**Comment by J-Pabon** [comment]
Closed here: a52ce2f85936cf5a846064f58b661d11ef517c79
