### ISSUE TITLE
Figma: UI recommendations

### ISSUE THREAD

**Issue by J-Pabon** [equalitie/ouisync-app#145]
- [x] ~~SettingsPage~~
  - [x] ~~Version number need to be next to app~~
- [x] Share modal
  - [x] Less space between radio button and text
  - [x] Icons (copy, share link) should be in the left side, and text on the right
- [x] Password text input in dialogs
  - [x] Blue line need to continue under the icon (eye icon, show password)
- [x] Left alignment
  - [x] Text always next to the icon, with left alignment
- [x] Repositories modal
  - [x] Less space between repositories list and actions
- [x] Use new illustrations for placeholders
- [ ] Use icons provided
  - [ ] https://figmaresources.org/
  - [ ] https://www.figma.com/community
  - [ ] https://thenounproject.com/

**Comment by IvanaBlzvc** [comment]
This issue seems to have got a bit out of date, so closing as it would cost more time to bring it up to date then to start a new one.
