### ISSUE TITLE
Find a way to not include firebase dependency in non firebase flavors

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#151]
Users may (rightfully) take issue with firebase being in the package as a dependency. We also don't know whether firebase does something even if not initialized. And finally third party installers such as F-Droid will not accept an apk if firebase is a dependency (whether initialized or not).

**Comment by inetic** [comment]
Right now this doesn't seem to be possible:

https://github.com/flutter/flutter/issues/46979

It's not super pressing, so maybe let's wait a little longer, if they won't implement it then maybe we'll find other solution (in the worst case we can have a script to rewrite the yaml file as well as some source files).

**Comment by IvanaBlzvc** [comment]
we no longer use firebase.  closing.
