### ISSUE TITLE
When creating a new repository, don't show warning messages until needed

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#157]
When creating a repository, the repository name text field is initially empty. This triggers a warning (red) message saying "Please enter a valid name.". This message in particular should IMO be shown only once the user tries to proceed with the repo creation.

**Comment by IvanaBlzvc** [comment]
Retested with build 57119efa
When creating a new repo, if a user tries to tap on create before they enter the repo name, there is a warning message 'please enter a valid name'.  This is solved, closing ticket.
