### ISSUE TITLE
Do we need to ask the user for "send you notifications" permissions?

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#162]
This seem to be happening only with recent android versions. I have a hunch this should be needed only if we wanted to show the user notification messages and not necessarily to show that the application is running in the background (background service icon).

So we need to investigate where this request is coming from and try to remove it. Also, if it is indeed required, what happens when the user presses "Don't allow"?

**Comment by J-Pabon** [comment]
It is correct that it happens only on recent versions.

It also seems to be true we don't really need to display the notification -tho I believe it is good to do it, so the user is aware the app is running in the background.

On a Pixel 5, Android 13:

- Right after installing the app, the notification telling the user the permissions that will be ask for and how they are needed, the initialization fails:

[` hasPermissions = await FlutterBackground.initialize(androidConfig: config);`](https://github.com/equalitie/ouisync-app/blob/68d4701f70ebf228dbc7067d3f78b664686ac27d/lib/app/utils/platform/platform_background_manager_mobile.dart#L39)

- On the second run (the app was closed and re-opened), the initialization succeeds, while at the same time, the dialog asking the user for the notifications permission is shown. Regardless of the user answer, the initialization will keep succeeding, and the only difference is the presence or not of the notification. 

I am looking into the reason for the delayed operation for the notification permissions and how it is related with the initial failing of the initialization.

**Comment by J-Pabon** [comment]
There is an issue in the plugin repository about this problem:
[[BUG] FlutterBackground is not initialised after letting app run in background](https://github.com/JulianAssmann/flutter_background/issues/56)

The workaround found there seems to work for now: https://github.com/JulianAssmann/flutter_background/issues/56#issuecomment-1218307725
