### ISSUE TITLE
Download file from repo - user cannot select destination? 

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#163]
Version: Master 66e5480a

**STEPS TO REPRODUCE**
- create a repo and add a file to it
- tap the three dots next to the file name, this opens the File Details menu
- select the first option: Download, which brings this popup 
![Screenshot 2023-01-11 at 10 46 15](https://user-images.githubusercontent.com/121942562/211773021-4e3bf41d-0a66-4728-91ca-21568710f466.png)
**SCENARIO 1** **Use External Storage is OFF**
- tap on the three dots 
![Screenshot 2023-01-11 at 10 47 30](https://user-images.githubusercontent.com/121942562/211773266-c8906cfb-150d-46e4-b2fa-e00f15a46354.png)
- this tap leads to the following screen
![Screenshot 2023-01-11 at 10 48 52](https://user-images.githubusercontent.com/121942562/211773516-fce59938-ebab-49e8-88af-042773512391.png)
- the screen is blank - so user doesn't get a chance to select the destination. 
**EXPECTED RESULTS** 
user is able to select the destination folder when they want to download a file from a repo

**SCENARIO 2** **Use External Storage is ON**
- just noticed that when this setting is off, the text in the Destination box is: /storage/emulated/0/ and when this setting is ON the text is the same, the only difference is the absence of the last forward slash /storage/emulated/0 (not sure if that is relevant)
- And also - what is the 'external storage'?  For users it will most likely mean USB key or SD card. If I attach a USB key to my phone, and go to the phone file manager, then I can see my USB drive there, but I cannot see it from within the ouisync repo so even when I choose to download a file with the 'external storage' = ON, I don't see that 'external storage', so cannot do it.  
![Screenshot 2023-01-11 at 10 58 03](https://user-images.githubusercontent.com/121942562/211775832-61c7b12a-f451-40c5-822f-0bcced934e47.png)
- I tap on the three dots within the Destination box, and I see this screen
![Screenshot 2023-01-11 at 11 00 24](https://user-images.githubusercontent.com/121942562/211776290-da080ca2-b853-43a0-82d9-8003f87596fa.png)
- This seems OK, I can select one of the offered folders todownload my file to
- I select Pictures 
![Screenshot 2023-01-11 at 11 02 21](https://user-images.githubusercontent.com/121942562/211776734-fbebfaaa-4b8b-431c-ae97-57d8f0a3bdd0.png)
- I tap the button at the bottom 'Save the file to this folder'
- And then I see this screen again 
![Screenshot 2023-01-11 at 11 03 58](https://user-images.githubusercontent.com/121942562/211777041-e32d0370-cf8a-47fd-8568-6fa5da3126d3.png)

**EXPECTED RESULTS** 
- When the user does select a folder to download the file to, there should be some kind of confirmation message when the download is finished
- The user should then (maybe) be offered to download another file or return to the repo.  If the user chooses to download another file, then the next thing that they should see is indeed 
![Screenshot 2023-01-11 at 11 03 58](https://user-images.githubusercontent.com/121942562/211777041-e32d0370-cf8a-47fd-8568-6fa5da3126d3.png)
- but if they don't want to download any more files, then this screen is not necessary.  
- and maybe the Destination box should be updated with the name folder that the user selected instead of /storage/emulated/0/ - not clear what this text is telling the user? 
- When I select 'external storage' = ON, I expect to see my USB key or SD card and to be able to download file from ouisync onto there.

**Comment by inetic** [comment]
@IvanaBlzvc I modified the dialog a bit in commit f3ce04bf3c3934b8015c974cbd2d5e9aae3d8064 and some of the above issues should now be resolved. Please have a look.

**Comment by IvanaBlzvc** [comment]
@inetic Retested with build 916cbe30 = not OK yet, but almost there 
### steps to reproduce 
- go to the three dots next to the file name within a repo
- from the menu, select the option Download 

![Screenshot 2023-01-20 at 12 06 06](https://user-images.githubusercontent.com/121942562/213680886-07b218db-f87a-4e1d-a66d-30eef0a22bce.png)
- tap on the three dots here to select the destination
![Screenshot 2023-01-20 at 12 06 45](https://user-images.githubusercontent.com/121942562/213681493-3b2893e8-1cfd-4c7b-a468-937f15cd2a14.png)
- then tap on the upward arrow on this screen
![Screenshot 2023-01-20 at 12 07 08](https://user-images.githubusercontent.com/121942562/213681612-ab5f5393-40f4-4902-9480-71dcded20c51.png)
- and that opens the file manager, which makes it possible to select a folder where the download needs to be done
- I selected the folder called Pictures
![Screenshot 2023-01-20 at 12 07 35](https://user-images.githubusercontent.com/121942562/213681821-00396d3c-af2f-4f05-9350-6dfe894e7c6c.png)
- tap on the blue button Save at the bottom of the screen and that brings the user here 

![Screenshot 2023-01-20 at 12 07 56](https://user-images.githubusercontent.com/121942562/213681987-b867aca2-4c42-4d15-8146-759cfa806cbd.png)
- we can see the correct folder name is displayed. 
- Tap the save button and then go to the folder Pictures to verify that download has been done correctly
![Screenshot 2023-01-20 at 12 08 48](https://user-images.githubusercontent.com/121942562/213682125-723f0d3a-1691-4cb4-bb6f-2f5d204edc02.png)
- Actually, as the above screenshot shows, the download was done, but not in the selected folder (Pictures) but in the download folder (which appears as a default at the beginning)

**Comment by inetic** [comment]
Forgot to actually use that directory. Should be fixed now by https://github.com/equalitie/ouisync-app/commit/c13323f1fc34ca2cdc1e66e311de9b45c00095fc . Can you please retest?

**Comment by IvanaBlzvc** [comment]
Retested with build 9dd9cf05 = OK on Huawei device Android 10 EMUI 12
