### ISSUE TITLE
Renaming a repo causes it to be permanently locked

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#164]
Version Master 66e5480a

### Steps to reproduce

- select a repo and rename it
- this locks the repo

### expected results
- entering the password (or biometrics) should unlock the repo

### actual results
- repo remains permanently locked. 

Can be reliably reproduced.

**Comment by inetic** [comment]
One issue was that the app did not remember (in Settings) that it's been renamed. This is solved in 3a0658cf5aaa21c5dda27052416a5fad014c8658, but some issues still remain. Mainly that the biometric storage remembers repos by name and so we either need to rename it there as well or store biometrics using non-name key (e.g. the info hash).

**Comment by inetic** [comment]
OK, the issue should now be fully fixed as of 085a6b7971d98fcb491a62cea20cfe1df9e9c8b6

**Comment by IvanaBlzvc** [comment]
retested with build 916cbe30 = OK
A repo can be renamed and opened after a password is entered
