### ISSUE TITLE
Reading non OuiSync QR codes crashes the app

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#166]

**Comment by IvanaBlzvc** [comment]
retested with build 916cbe30

When I try to scan a QR code off the net, or one of Briar's QR codes, nothing happens on the screen.  Scanning doesn't seem to take place.  Is this the expected behaviour, @inetic 
If so, we can close this.

**Comment by inetic** [comment]
>  Is this the expected behaviour, @inetic

Yes, that's expected. Thanks
