### ISSUE TITLE
Add a message to the user to keep the password safe - when password generated automatically and no biometrics

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#169]
### steps to reproduce

- create a new repository
- when asked to set a password for it, select the 'generated' option
- 
![Screenshot 2023-01-13 at 11 19 00](https://user-images.githubusercontent.com/121942562/212634266-9a6d50f4-853e-4375-98de-f772c680b8e4.png)

- as these automatically generated passwords are difficult to remember, it may be useful to remind the user that they need to keep these pwds somewhere safe - otherwise if they lose them they won't be able to use the repository in question
- this may be similar to what is being done when the user select the biometrics'option, but in the case illustrated here, the password is automatically generated and the user did not select the biometrics.

**Comment by J-Pabon** [comment]
@IvanaBlzvc one question:

When creating a new repository, the dialog should have two switches at the bottom: Generate password, Secure using biometrics.

![image](https://user-images.githubusercontent.com/13749449/213104686-173465a1-643b-4268-8cd9-258177f9442e.png)

When the user toggle the one for biometrics to the false position, a message alerting the user to save the password is displayed.

In the screenshot you have, the **Secure using biometrics** seems to be missing. Is this the case?
Where are you opening this dialog from: the main screen when there are no repositories, or from the bottom dialog opened using the top bar with the current repository name?

**Comment by J-Pabon** [comment]
Wait, @IvanaBlzvc 

Is it possible that the phone on which this happens doesn't have biometrics, so that option is not visible?

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

Please re-test this issue (commit f53a991ecf4dc9779fd36af5aeb7d89b64640638)

**Comment by IvanaBlzvc** [comment]
re-tested with build 916cbe30. 
The red warnign message to keep the password somewhere safe is implemented. 
![Screenshot 2023-01-20 at 10 28 09](https://user-images.githubusercontent.com/121942562/213677238-d8e58388-f69b-4a69-8b2b-f92343dde88a.png)
