### ISSUE TITLE
Incorrect message when sharing a repo with write permissions

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#170]
build 085a6b79

### steps to reproduce 
- Create a new repo with write permissions
- then tap on share here 
![Screenshot 2023-01-16 at 14 52 00](https://user-images.githubusercontent.com/121942562/212697120-b7ad124e-7c6f-46b5-934c-0212edcc6412.png)
- the share screen opens and on that screen, select read or blind permission for sharing this repo. In both cases, this is the message given to the user
![Screenshot 2023-01-16 at 14 57 55](https://user-images.githubusercontent.com/121942562/212697422-72aaabd9-1080-404d-b1e0-f48c70a5ce36.png)

### actual results
- this message is not correct for this situation. 
### expected results
- The read and blind are lower permissions then the write and this message should not be shown here

**Comment by IvanaBlzvc** [comment]
the same message appears when I select write as well.

**Comment by inetic** [comment]
Should be fixed by 39ba4e3a38a487891f87a131f3f56ade282cb0d4

**Comment by IvanaBlzvc** [comment]
Retested with build 5d709c5d = OK.  No messages are shown to the user at this point.. the user is able to select the level of permissions and share the link.

**Comment by IvanaBlzvc** [comment]
When a user adds an existing repo (by typing in the link or scanning the QR code of another repo) then that nwly added repo can have blind, read or write permissions.  If they then want to share it again, they can share it either with the same permissions or lower ones.  
retested build 916cbe30 = OK
