### ISSUE TITLE
'secure using biometrics' not visible when a new repo is created

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#171]
build 085a6b79

### steps to reproduce 

- when creating a new repo, the user is asked to either enter the password or to generate it
![Screenshot 2023-01-16 at 16 34 28](https://user-images.githubusercontent.com/121942562/212717036-ebfc7147-c194-4630-bfcf-c7ebd3c48b9b.png)
- however, if the same repo get's locked, to unlock it the user sees this screen
![Screenshot 2023-01-16 at 16 04 36](https://user-images.githubusercontent.com/121942562/212717202-f69b1ce1-376d-4b80-b9dd-ec4295a84898.png)

### expected results
- I would expect that the user is given the oppotunity to set up their biometrics credentials at creating the repo, and not at the point of unlocking it.  
- When the user needs to unlock the repo, they need to be given the option to unlock using their biometrics that they have previously set up?  

### actual results 
- user is not given the opportunity to set up their biometrics at the point of creating a repo. 
- and therefore user is not given the opportunity to unlock the repo using their previsouly set up biometrics

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

You can re-test this issue (commit c24c9c0194308ba0e3cbd1e02da2e8bc378b8bc1)

**Comment by IvanaBlzvc** [comment]
Retested. When the user sets a fingerprint on their device, then they see the field 'secure using biometrics' when creating a new repo.  But not when they set a face recognition.  @J-Pabon is investigating the android library in question aiming to better understand why the face recognition is not 'picked up' and therefore why in this case the 'secure using biometrics' is not displayed to the user.

**Comment by IvanaBlzvc** [comment]
https://mattermost.equalit.ie/equalitie/pl/1yxrz19nsibmmbm93wx8nrz7hy assigning to a later milestone as agreed

**Comment by IvanaBlzvc** [comment]
As per call with Leah 14/02/2023, in android device the use of face recognition is not very common.  To re-test when the UI is changed according to the changes agreed in the same call. 
https://www.figma.com/file/MW0moWIc6cZKw8TpY3XXX5/OuiSync----UIUX?node-id=1672%3A14816&t=SWWzEcW9qRdaTjz3-0

**Comment by IvanaBlzvc** [comment]
Use is able to protect a newly imported or created repo with biometrics now... 
![Screenshot 2023-08-16 113135](https://github.com/equalitie/ouisync-app/assets/121942562/c5e964d1-acea-491c-afdb-8acf214612dd)

tested with 1993c4b0 = OK
