### ISSUE TITLE
When adding a new 'blind' repo, remove the red warning message to keep the password safe

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#177]
Build 916cbe30

### steps to reproduce
- tap on the add an existing repository button 
- 
![Screenshot 2023-01-20 at 11 03 40](https://user-images.githubusercontent.com/121942562/213668846-770b1885-bd43-4c39-9fdd-36b41c210efd.png)
- and they scan the QR code of one existing repository which is shared 'blind'
- there is no opportunity for the user to set up a password for that repo, but the warning to keep the password safe is still there
- 
![Screenshot 2023-01-20 at 10 28 09](https://user-images.githubusercontent.com/121942562/213669029-bd1a073a-c076-4c86-8f52-73594ee345fe.png)

### expected results
- the red warning should not be shown to the user in this case

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

I can't reproduce this. Can you please uninstall the app, get the latest changes from master and try again?

**Comment by IvanaBlzvc** [comment]
@J-Pabon Retested with the branch 
![Screenshot 2023-01-24 at 12 36 23](https://user-images.githubusercontent.com/121942562/214281839-693e83e4-c0d8-45fa-9236-3ae8f38dcd93.png)
it's looking good - no wrning message appears when importing n existing blind repo
![Screenshot 2023-01-24 at 12 35 23](https://user-images.githubusercontent.com/121942562/214281915-d73345ea-ba6f-4d48-9daa-f67678addc26.png)

**Comment by J-Pabon** [comment]
Closed here: 49792e95033977182af616be2c4c7faf52abac34
