### ISSUE TITLE
Tapping lock after renaming a repository, causes app to exit/crash?

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#180]
Build 9dd9cf05

### steps to reproduce
- create a repo (or import one)
- go to settings and rename it
- after renaming it go to the repo screen
- 
![Screenshot 2023-01-27 at 12 40 16](https://user-images.githubusercontent.com/121942562/215079817-a8ae95f4-454b-46b0-a0a3-261b0a406dde.png)
Tap the lock

### Expected result
- user can lock the repo
### Actual result
- app exists/crashes
here is a logcat logfile - I hope it contains useful info

[Lock after renaming repo - crash.txt](https://github.com/equalitie/ouisync-app/files/10518526/Lock.after.renaming.repo.-.crash.txt)

**Comment by IvanaBlzvc** [comment]
Retested this with build 9dd9cf05 - still the same

**Comment by J-Pabon** [comment]
@IvanaBlzvc 

I couldn't reproduce this. 

After renaming a repository and going back to the main screen, the repository is already locked. Is it different for you?

**Comment by inetic** [comment]
I think this may have been fixed by fixing the repository renaming. So maybe just retest it and we can close it.

**Comment by IvanaBlzvc** [comment]
The crash also happens when the user clicks or taps on the padlock when it shows 'locked'... it happensboth on Android and on Windows.  Closing this ticket and reporting a new one as this issue does not seem to be related specifically to renaming.
