### ISSUE TITLE
Renaming a repo - implement a solution that does not lock a repository when it is renamed

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#204]
The steps to reproduce the issue

- Create a new repo
- Go to settings 
- Rename it (for example because you mistyped its name and you want to correct it)
- After that, try to share it

On the sharing screen where the user is supposed to select the permissions to share the file, only Blind is enabled at this point. 
This is because renaming the repo actually locks the repo. 
However, the user doesn't know that this is the case, and they may be wondering why the only permission enabled is the 'blind' one? 

"Right, it's a technical issue: when we rename a repository, what happens is that we rename the database file. And when we rename the file we need to close it and then reopen it and needs to be unlocked again." https://mattermost.equalit.ie/equalitie/pl/3tqpajz333bbtn9trhurf5mkkh

To fix: 

" you could ask the library for a share token before the repo is closed and then use it to unlock it once its open again." https://mattermost.equalit.ie/equalitie/pl/q4ek4qfu4ifq5r9y53zjrker4o

When fix: to retest and ensure that renamig a repo doesn't lock it; when the user tries to share it, all three permission levels are available to them.

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

You can re-test this one with the latest commit in master (20b35f711e22872a4ec9b90660957f07da86d541)

**Comment by IvanaBlzvc** [comment]
re-tested with build ec55c632 = OK
