### ISSUE TITLE
Windows - implement data entry using 'enter' button in addition to cliking on onscreen buttons

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#205]
At the moment, every time user enters  password, repo name or similar, if they want the data to be saved, they need to click on the onscreen buttons provided in the windows app.  For users' convenience,though, it would be nice to be able to also save the data by pressing the enter button on the keyboard.
https://mattermost.equalit.ie/equalitie/pl/6p8fdyzht3gjbnpnxicu3uirsc

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

Can you please checkout this branch [form-focus-keyboard-action](https://github.com/equalitie/ouisync-app/tree/form-focus-keyboard-actions) and test this?

Thanks!

**Comment by IvanaBlzvc** [comment]
Data can be saved by hitting the enter key on the keyboard when the enter button (on the dialog box) is in focus.  Tested with 0.7.8 = OK
