### ISSUE TITLE
Windows app - clicking on Scan QR code gives an exception

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#210]
![Screenshot 2023-02-20 140750](https://user-images.githubusercontent.com/121942562/220117748-2181d903-ed19-4e23-80a4-980e49659e9d.png)
Steps to reproduce 

- go to add existing repository in the windows app
- click on the Scan QR code

In the Visual Studio there is an exception (see attached screenshot) and nothing happens when the used clicks on that button.  
Is the windows app going to be able to scan the QR code as well?

**Comment by IvanaBlzvc** [comment]
As per call 21/02/23 the button 'scan QR code' can be removed from windows app

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The plugin mobile_scanner, which we use for reading the QR, does not support Windows or Linux.

So in this platforms, we can just disable the button and show a message.

The fix is already on `master`: fd064c0b414b03ea050aa6ea2198aa47d307625f

**Comment by IvanaBlzvc** [comment]
The scan the QR button has bene disabled on windows... closing the ticket 
![Screenshot 2023-03-01 102802](https://user-images.githubusercontent.com/121942562/222098640-93e483d4-6ddb-4ef6-b213-351b33582db0.png)
