### ISSUE TITLE
Implement: Allow user to create or import repositories without password

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#215]
- user should be able to create or import repositories with or without password (at the moment they are forced to create password for each repository which was a solution too cumbersome to the user). 
- if the user creates/imports repository with password (or biometrics), then they should be given an option later on to remove that password (or biometrics)
- if the user creates/imports a repository without password, then they should be given an onscreen option to add password later on (or add biometrics protection). 
 @jorge when you implement it, don't close it, but assign to me for testing?
Thanks.

**Comment by J-Pabon** [comment]
Got it.

When I'm done with what I'm working on currently, this will be included (except the option for "removing" the use of a password, maybe... Or maybe not, l'm not sure yet)

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

> user should be able to create or import repositories with or without password (at the moment they are forced to create password for each repository which was a solution too cumbersome to the user).

You can retest this issue with the latest commit in `master`.

**Comment by IvanaBlzvc** [comment]
User is able to create a repository without setting up password protection for it.
