### ISSUE TITLE
User unable to upload new version of an edited file

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#217]
### Steps to reproduce: 

- upload a file into ouisync from a folder on your device
- then edit it and try to upload again - to create a new version

### Expected results: 
- user is able to upload a new version of the previously uploaded file
- if the file alrady exists, then the user is given the option to decide if to overwrite the old file or to create a new version of the same file.
### Actual results
- user gets a toast message telling them that this file already exists in the repository, but they are not given the prompt to decide if they want to overwrite the existing file or create a new version of it

**Comment by IvanaBlzvc** [comment]
@inetic I assigned it to you - please reassign as needed

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

This fix is already merged into master here 1d956173b534232470d1fe977aee19a42c3f3e97

**Comment by IvanaBlzvc** [comment]
@J-Pabon retested with master version 747a58fd = OK on Windows, on Android 10 (Huawei device).  Androoid 12 - the build fails... but that's a separate issue.  Android 11 = OK (Xiaomi device).  Closing ticket.
