### ISSUE TITLE
To separate the general app settings and repository settings 

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#220]
At the moment, 16/03/23, bild 5b4b055e, The 'home page' listing all the repositories has been implemented. 

This page has the blue Ouisync title bar at the top, with the settings button in the upper right corner. 

![Screenshot 2023-03-16 at 14 05 48](https://user-images.githubusercontent.com/121942562/225626108-da7447fe-5385-4e8d-83aa-0401923b5ff9.png)
As this screenshto shows, the repository settings need to 'move' to the three vertical dots next to each repository' name. Only the general settings that apply to the whole app should open when the user taps 
![Screenshot 2023-03-16 at 14 08 09](https://user-images.githubusercontent.com/121942562/225626427-96e9e40f-fac9-48de-a9f4-0aa6066e8b72.png)

**Comment by J-Pabon** [comment]
Updated to wireframe here: [Figma - High Fidelity](https://www.figma.com/file/MW0moWIc6cZKw8TpY3XXX5?node-id=1672:14816#427289688)

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

You can use the latest commit on master for retesting this, here 1cd87090a9028e2c8f7e29f25bd27cc3f9f05f60

**Comment by IvanaBlzvc** [comment]
done
