### ISSUE TITLE
Unlocking a repository protected by biometrics - briefly showing two progress wheels

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#225]
When unlocking repository protected either by biometrics or pin, two progress circles are shown on screen - albeit very briefly.  See attached. 

https://user-images.githubusercontent.com/121942562/228512785-8c66d56f-46b6-474c-ab74-9ba4f7c3105d.mp4

**Comment by IvanaBlzvc** [comment]
Tw progress circles show briefly also in ths case; 
Run the ouisync and while the app is in the foreground, lock the phone (ie make the screen black). 
Then unlock the phone using your fingerprint.  

First there is a blank screen for a second or two, and then ouisync screen is shown, and the user can briefly see two progress circles.

**Comment by IvanaBlzvc** [comment]
on Huawei Android 10 - two proress circles when restarting the app.  I close the app and then restart it, and while the 'home screen' is loading, there are two progress circles - on on the top blue bar, and on on the big white screen underneath.

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

This fix is merged on master here 7ba3c52c95f7c64fb09cd1073232e1b781696d25

**Comment by J-Pabon** [comment]
> on Huawei Android 10 - two progress circles when restarting the app. I close the app and then restart it, and while the 'home screen' is loading, there are two progress circles - on on the top blue bar, and on on the big white screen underneath.

This is not a bug, but a feature (now I sound like Microsoft).

I mean by this:  the two progress indicators are expected to be there, since two different widgets are loading at the same time.

The question  is:  do we want this? or maybe just keep the main one and remove it from the repository bar?

**Comment by IvanaBlzvc** [comment]
as expected.
