### ISSUE TITLE
When user taps 'move' in the file settings, there is another navigation arrow in the top bar

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#232]
### Steps to reproduce 

- import a file into repository
- then go to file settings (three dots on the right of the file name)
- select Move
### Actual results 
In the top bar the user can see two navigatio arrows... 
### Expected results
there should be just one navigation arrow in the top bar
![Screenshot 2023-04-13 at 11 27 29](https://user-images.githubusercontent.com/121942562/231727973-1e9bacb0-c9c9-490d-aa07-2fce0e10071d.png)

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix is already merged, here ddebae3ad74b7af930a0c9aa8c08877c65f9729a

**Comment by IvanaBlzvc** [comment]
retested with build ec55c632 = OK, closing
