### ISSUE TITLE
File Settings - Sharing file via email from a mobile device -incorrect email address in the 'TO' field

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#233]
### Steps to Reproduce 

- Import a file into a ouisync repository
- Then go to file settings and select 'share'
- This will open a screen on which the user can select a messaging app they want to use to share the file

Try: whatsapp, viber, MMS or SMS, gmail

I did not succeed in sharing the file using any of the messaging platforms, but I did using the gmail... 

When I selected gmail, a draft email was automatically created, and it had the 'from' address of that email account (= OK), in my case that was brairabc@gmail.com.  In the TO field, it had this 
"//0@org.equalitie.ouisync.pipe/736699/IMG-20230404-WA0003.jpg"

Following a chat in MM? this is not correct, so reporting it here (link to the conversation : https://mattermost.equalit.ie/equalitie/pl/1si3p6mbiif15efsfxnpffwq9w )

The file that I wanted to share is attached to the email as an attachment, that is probably OK

There is still one clarification that is needed: shoudl this file be shared unecnrypted - so that the chat apps like whatsapp or viber can recognise the file format and permit it to be shared?

**Comment by IvanaBlzvc** [comment]
If the file sharing is supposed to be possible via messaging apps, do the files need to be unecnrypted so that the chat apps can recognise the file format and allow the sharing?  (at the moment they don't)?

**Comment by J-Pabon** [comment]
> If the file sharing is supposed to be possible via messaging apps, do the files need to be unecnrypted so that the chat apps can recognise the file format and allow the sharing? (at the moment they don't)?
> 
> If it is necessary for the individual files to be unencrypted for saring via other apps, then the users should be warned? (Maybe this is completely the wrong thinking.. just trying to speculate?)

Yes, this requires the file to be unencrypted so it can be shared with other apps. 

However, the file is kept in memory, not saved to the device storage; so this is a secure way to do it.

**Comment by J-Pabon** [comment]
This fix is merged into master here ec55c63289aac1b8d4db4ef8ec5ca3acbd228fab

**Comment by IvanaBlzvc** [comment]
Retested with master build ec55c632 = OK

**Comment by IvanaBlzvc** [comment]
I am able to share the individual files via whatsapp, MMS, gmail etc...
