### ISSUE TITLE
To imrove the oncreen message when removing biometric validation

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#238]
Currently, if a user has biometrics authentication set up for a repository, and then they remove it, they see thismessage 
![Screenshot 2023-04-22 at 13 19 55](https://user-images.githubusercontent.com/121942562/233781229-67d6734a-f5ff-4f57-bda1-74c2593590ce.png)
-  But, with a view of the fact that the user doesn't have to have a password at all, this message may not always make sense. 

- If the user does set up a local password, and then they tap on the 'eye' icon, they can see the local password - so the messages is not entrely correct.

**Comment by inetic** [comment]
Yeah, maybe let's just remove the message.

**Comment by IvanaBlzvc** [comment]
@J-Pabon just agging you, to make sure you didn't miss this little thing

**Comment by J-Pabon** [comment]
@IvanaBlzvc this is fixed in master here ff1e7024277f2bd69634215787f04a8bf60247b4

**Comment by IvanaBlzvc** [comment]
Message is removed.  The user can switch the biometrics validation on or off withoutthe red message appearing.
