### ISSUE TITLE
Untrusted devices

### ISSUE THREAD

**Issue by trymeouteh** [equalitie/ouisync-app#240]
Please allow for untrusted device just like Syncthing offers.

Untrusted devices are devices that will store the synced files and folder with E2EE so the device owners cannot decrypt them.

Useful for when using ouisync on a server that is hosted by a third party but do not want the third party to see the files and folders your syncing.

**Comment by inetic** [comment]
Hi @trymeouteh, this feature was one of the main ones when designing the protocol and storage format. So it is already supported. Not only that, apart from encrypting the file contents and file/directory names, we also encrypt other meta data such as the directory structure and file sizes. For this we borrowed some ideas from [CryFS](https://www.cryfs.org/).

To store your data on an untrusted device, all you have to do is create a **blind** share token in the sharing dialog and import it on the other device. With a **blind** token the other device will only be able to store encrypted blocks, but not read nor write the repository.

For completeness, I'll just mention that with the **read** share token the device that imports it will only be able to read the repository but not write into it. And of course with the **write** share token the other device will be able to read and write into it.
