### ISSUE TITLE
Implement share, save and view logs on Windows UI

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#256]

**Comment by madadam** [comment]
Save and view now work on Windows and Linux  (https://github.com/equalitie/ouisync-app/commit/e1708ab9a72f839e55040fe1ce50a3ef11d922b6). It's unclear how to implement Share and whether it should even exist on desktops.

**Comment by IvanaBlzvc** [comment]
Save and view logs on windows now works;  tested with master 1993c4b0 = OK
