### ISSUE TITLE
Implement the badge that warns the user that the app is not allowed to run in the background

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#257]
This is for the user that choose not to allow the app to runint eh background (probably because they are saving battery)
- if the user selects to switch off the battery optimisation and the app is allowed to run in the background, then the badge shoudl not be showing
- if the user does not switch off the battery optimisation, then the badge should show
- and if the user selects to switch off the battery optimisation, but the app (for some reason) doesn't run in the background.. the badge should be showing
- the badge is showing as a little red dot on the gear icon
- when the user taps the gear icon, the app settings will open, and the user will have a chance to switch off the battery optimisation... 
This was talked about at today's standup with Jorge and Peter.. .the details of implementation to be worked out - in coolaboration with Leah.

**Comment by inetic** [comment]
This should now be done
