### ISSUE TITLE
Local discovery should 'discover' only those peers with whom a repository was previsouly shared

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#259]
https://mattermost.equalit.ie/equalitie/pl/fzzk4msb43b78c4mkdfx388frw

**Comment by inetic** [comment]
This isn't doable. The discovery and then the protocol deciding which repositories are shared among peers are done in two separate steps.

In the first step peers find and connect to each other. Even if they don't share any repositories now, that may change in the (near) future, for example by those users showing the QR share token to each other. So the peers need to stay connected to each other and each time there is a repository added to any of them, they need to communicate the fact and start syncing if new repository is present on both devices.

I'm going to close this, but feel free to reopen if you'd like to discuss further.
