### ISSUE TITLE
Imlement solution so that the ouisync app in Windows can run only one instance at one time.  

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#268]
Currently the app is able to start two instances, but cannot mount two ouisync drives therefore the user woudl see this error message. 
To Implement a single-instance solution.  

![Screenshot 2023-07-25 at 15 34 26](https://github.com/equalitie/ouisync-app/assets/121942562/ebc07405-9e0e-4bf4-bf67-96b0f9b3768c)

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

This fix is already on `master`: 886ea83dec62cfc21cdaf7ce49d6991611a19e74

**Comment by IvanaBlzvc** [comment]
retested with 1993c4b0 = OK
