### ISSUE TITLE
Dokan installation for Windows - implement automatic installation 

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#269]
![Screenshot 2023-07-25 172825](https://github.com/equalitie/ouisync-app/assets/121942562/155a6f44-2e17-441a-97d1-0ef9daca0f9f)
If a user doesn't have Dokan installed on their windows machine, then they can still install the ouisync app, and they will see this message in the ouisync logs 
 
User then has to download and install dokan and restart the ouisync app - the red message then disappears. 

However, in the future, dokan should be bundled with windows installer 
Conversation in MM... 
To improve the user's experience, we could install dokan automatically and we will plan it for the future app improvements. 
P: Note that we can't use msix chainging for this one because we're not installing using msix (something we discussed previously). There might be other workaround though.

A: Are we using inno setup?

P: yes
A: I'm looking at its docs. It seems we can define programs to run as part of the setup:  https://jrsoftware.org/ishelp/topic_runsection.htm Maybe we can bundle the dokan installer and run in like that?

    "Maybe we can bundle the dokan installer and run in like that?"

Maybe yes, I think though there are some details to be sorted. Such as what if there is already dokan installed? Or whether we want to uninstall it during ouisync uninstallation.

**Comment by IvanaBlzvc** [comment]
Tested with version 0.8.0 20240404 (.exe)
After installing the ouisync app for the first time, the user is gien a dialog box with exaplanation that they also need ot install dokan.  Clicking on the install button starts the dokan installation.  
After the dokan installation is finished, the red dot still shows... when the user clicks on the red dot, there is no warning in the settings.  
If the user restarts the app, the red dot disappears. 

Two small issues here: 
- the red dot should not be showing after successful installation of dokan
- the app should not require restart to hide the red dot

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix is already in `master`, here: 3d82608361f6f1e5561a03eb78d0e0d32130d653

**Comment by inetic** [comment]
Done
