### ISSUE TITLE
[Windows] Image preview on Windows only load the image half way

### ISSUE THREAD

**Issue by J-Pabon** [equalitie/ouisync-app#272]
After tapping on a image in Ouisync, the Photos app (or whatever is the default in the PC) is launched to display it (OK), but it is not loading correctly (!):

![image](https://github.com/equalitie/ouisync-app/assets/13749449/02d11fb2-db64-4c04-b34b-52669492273d)

If the same image is downloaded from Ouisync to the hard drive and then opened it, it loads ok.

**Comment by inetic** [comment]
Likely related to https://github.com/equalitie/ouisync-app/issues/387

**Comment by IvanaBlzvc** [comment]
retested with RC ouisync_0.7.8-20240117111245.50409491 = OK
