### ISSUE TITLE
[Windows] Single instance not working when minimized to system tray

### ISSUE THREAD

**Issue by J-Pabon** [equalitie/ouisync-app#274]
When the app is minimized to the system tray, if the user tries to open another instance it won't reuse the current one.

If the app is not minimized to the system tray, it works as expected: the instance already in use is returned (bring to the foreground).

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix to this is already in `master` here f630aa419d6a0bffc3168e771a7c048a40b898d9

**Comment by IvanaBlzvc** [comment]
retested with master 1993c4b0 = OK
