### ISSUE TITLE
Unable to select the folder where to download the files from the windows ouisync app

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#276]
When I try to download the file from the windows ouisync app, I cannot seelct the folder that I want.  
First, when I click on the three dots in the file settings, I see this 
![Screenshot 2023-08-18 124436](https://github.com/equalitie/ouisync-app/assets/121942562/f0debb95-1a5c-4e96-a30e-b1bef1ef90e2)
which is OK.  Then I click on the three dots here, to select a folder other than the Downloads folder which is offered. 
I see this 
![Screenshot 2023-08-18 124642](https://github.com/equalitie/ouisync-app/assets/121942562/69669f56-ff94-4077-9557-b289aa02e156)
If I click on storage here, nothing happens, and I'm not sure what the Rufus folder is... 

Expected results: 

I want to selct the folder where to download the files to

Actual results: 
I can only download the files to the Downloads folder, and cannot freely select the folder of my choice.

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

You can test this with this commit in 'master': 2c1c08d6877f9aa3961f850c566f542ec19ccf1f

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

Please try again. The latest commit in `master`: a7ebca53e4a7aa851220c88c94ebee82cdf0b10a

**Comment by IvanaBlzvc** [comment]
Retested with the build [5ef92ea](https://github.com/equalitie/ouisync-app/commit/5ef92eacc5b51a64b223071da07558f4af8fb8cc) = OK

**Comment by IvanaBlzvc** [comment]
Closing

**Comment by IvanaBlzvc** [comment]
retester with 0.7.5 = OK
