### ISSUE TITLE
Count of Number of peers 

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#277]
Currently, the count of number of peers is done by counting each peer connection and not each peer. 
For example... 
![Screenshot 2023-08-18 at 10 47 58](https://github.com/equalitie/ouisync-app/assets/121942562/7dcb4f47-8ff0-45dc-b31f-6f7f04da1402)
For this situation the number of peers would be reported as 6/9
When actually there are only 3 peers connected nd the IP addess 77...204 is listed as 'connecting' twice... 
Expected results: 
to show the correct number of peers connected and to not count the double entries in the 'connecting' part... 
tested on 194e45d

**Comment by IvanaBlzvc** [comment]
Call 5/9/23 - maybe we can only show the first number 8/191... so show only 8? maybe we can have a toggle 'advanced info' regarding peers?

**Comment by IvanaBlzvc** [comment]
Following today's standup, the change to do regarding the peers counting is to show the number of peers connected, and not count all their connections.  
On the above screenshot that will be 3 and not 6. 
Other related changes are #352 and #310 - which contain changes in documentation and small changes in UI

**Comment by madadam** [comment]
Closed in https://github.com/equalitie/ouisync-app/commit/3ba6742fc747e06b91ec06089fc7105d4f111303

**Comment by IvanaBlzvc** [comment]
The number of peers is showing now like this 
![Screenshot from 2023-11-21 11-04-46](https://github.com/equalitie/ouisync-app/assets/121942562/7ab65fb3-ea5e-43ae-851f-8c2cd0443682)
Tested with linux package ouisync_0.7.5-20231121104418.3ba6742f_amd64.deb = OK
To retest on Windows and android with the next release candidate

**Comment by IvanaBlzvc** [comment]
retested wit 0.7.7 = OK
