### ISSUE TITLE
Sharing repository from Android > Windows by link -> link is clickable but does not lead the user to the app

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#278]
Sharing a repo from Android to Windows by link, via email. 
![Screenshot 2023-08-21 132628](https://github.com/equalitie/ouisync-app/assets/121942562/573d9ac8-5318-43e1-b447-65d1dca3bd75)

The link within the email seems clickable, but If I click on it, it leads me here 
![Screenshot 2023-08-21 131240](https://github.com/equalitie/ouisync-app/assets/121942562/9cae3731-903e-4340-bde9-ecd531851538)

**Comment by IvanaBlzvc** [comment]
"in any case, we would need to explicitly tell windows to create this association, either during the installation or maybe on the first time the app runs or something. "

**Comment by madadam** [comment]
Potentially useful: https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-app-with-uri

**Comment by inetic** [comment]
Duplicate of https://github.com/equalitie/ouisync-app/issues/367
