### ISSUE TITLE
In some cases Move button enabled when files cannot be moved to the location selected

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#280]
I have r1 that contains f1 and f2 folder.  f1 contains a file a.jpeg that I want to move to the root of the repor1.  

I select the file a.jpeg, and  I select the Move from the three dots menu.  The move button appears at the bottom, and it is disabled.  = OK

Then I tap on the back arrow in the top left hand side corner (next to the name of the repository) this will take me out of that repository and to the repo homepage (that list all the repos I have).  The move button is still disabled. = OK

I select another repository, the Move button is still disabled = OK (according to the current design)

I select the same repo, the move button is enabled = OK and i can select a folder or I can move the file to the repo root.  = OK

But... 

If I have a file a.jpeg in folder f1, repository r1, 
[12:48 PM](https://mattermost.equalit.ie/equalitie/pl/hoaqt589tbntpgqsf5hxahkzka)

If I select a file in the folder F1 and I tap move, and I navigate to the repo root by tapping the back arrow next to the folder name the Move button becomes enabled.  = OK

If from there I tap the back arrow next to the REPO NAME,it takes me to the repo homepage and the move button is still enabled.  = NOK

**Expected:** Because moving files cannot be done to the repo home page - when I am there the Move button should not be enabled.  

If from there I navigate to another repo (where currently I cannot move the file to), the Move button is still enabled... (NOK)

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix is already on `master`, here: 25ad9e8fea165f4ad1d84d438d4d6fa627872811

**Comment by IvanaBlzvc** [comment]
retested with 0.7.8 = OK
