### ISSUE TITLE
Wrong / missing app icon on linux

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#288]
On linux, the app icon doesn't show correctly: both the system tray and the alt-tab switcher show placeholder icons instead. 

(Ubuntu Ubuntu 22.04, Mate desktop)

**Comment by madadam** [comment]
Replaced the icon with one with higher resolution and transparent background. Looks good on my end.

**Comment by IvanaBlzvc** [comment]
re-tested with ouisync_0.7.5-20231120142152.1ce4e260_amd64.deb = OK
