### ISSUE TITLE
Windows app - Selecting the file settings > rename option doesn't work on the Focus branch

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#291]
Steps to reproduce: 
- using the tab key select a file in your windows ouisync app
- tab to file settings (the three dot menu)
- in the file details modal window, stab to the Rename option. 
- hit Enter key 
Expected results 
- Rename dialog box should open 
-
Actual results
- this is what the user sees on the Focus Form branch 
- 
![Screenshot 2023-09-15 111747](https://github.com/equalitie/ouisync-app/assets/121942562/21b73245-f049-44e0-8d36-d941828b3535)

This may have already been fixed onthe Master - to confirm and if so, then add the label To Retest and assign to me, please.

**Comment by J-Pabon** [comment]
Fixed here: 325ca791cee3ed950673326d755a870cb9cfa52b

**Comment by IvanaBlzvc** [comment]
@J-Pabon On the build 5ef92ea I am not able to rename the folder.  I am able to rename the file and repo, via file settings or repo settings.  But if I go to folder settings and select the rename option (using keyboard, but the same happens if I use the mouse as well) I am not able to rename the folder.  I type in the new name, click on Save, but nothing changes - the folder name remains the same as before.  See what happens when I rename the repo, versus what happens when I rename a folder. 

Uploading Ouisync 2023-10-19 13-52-51.mp4…

https://github.com/equalitie/ouisync-app/assets/121942562/aee4ecff-ef15-496f-b098-373168e5b2d5

**Comment by IvanaBlzvc** [comment]
Retested with 0.7.5 = OK
