### ISSUE TITLE
Windows app - Deleting non-empty folder gets two confirmation dialog boxes

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#293]
Steps to reproduce 
- in windows app select a folder that contains somefiles and then go to folder details (three dots menu)
- select delete option
Expected results: 
- the user gets one confirmation dialog box asking them if they are sure they want to delete the folder and all its contents
Actual results: 
- the user gets two confirmation dialog boxes... one after another.
![image](https://github.com/equalitie/ouisync-app/assets/121942562/30247496-074c-49f5-9933-1380a5707b22)
 This is correct;  But after the user hits Delete button they get another confirmation message 
![image](https://github.com/equalitie/ouisync-app/assets/121942562/6906c072-d2dd-4ee8-b388-2b2b206125be)

**Comment by IvanaBlzvc** [comment]
the same happens on android and linux as well.

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix is already on `master`, here: 52a98ae65d340df3d502f5aec97007d186756c2e

**Comment by IvanaBlzvc** [comment]
retested with 0.7.8 = OK
