### ISSUE TITLE
Linux app - unable to add a file to a repository

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#297]
Steps to reproduce 

- create a repository 
- click on plus button to add a folder or file to it
- add a folder, name it, click on Save.  
- this is OK
- Then try to add a file... by clicking on the file icon on the modal window
Expected: 
- able to upload a file 
Actual results: 
- Clicking on the file icon on the modal window - nothing happens.  
-

**Comment by J-Pabon** [comment]
For other OSes it is necessary to request permission from the user to access files; this is not needed on Linux, and because of this, the plugin used for the process doesn't support the platform.

Fix: only check for permissions if not Linux.

**Comment by IvanaBlzvc** [comment]
retested with version 0.7.3 = OK
