### ISSUE TITLE
Linux app - rename the GUI executable to `ouisync-app`

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#301]
The name `ouisync` would better suit for the CLI executable.

**Comment by inetic** [comment]
Or better I think to rename it to `ouisync-gui` as that seems to be the more standardized nomenclature.

**Comment by IvanaBlzvc** [comment]
14. dec 23 - hasn't been renamed yet, so keeping the ticket open (MM conversation, QA channel)
