### ISSUE TITLE
Improve user feedback when the user’s device doesn’t have the required app to open a file 

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#307]
(example: no pdf reader to open the pdf file present in ouisync repo )

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

This is on the latest `master`, here: 37a6226096547ff1114ddd781d8de6fe30207663

Try to rename the file, changing the file extension to something that makes no sense (for example: fgthy), then to another file extension that exist, but most likely there is not app for it (like `xyz`) that way you can see the different messages for this action.

When the action is successful, no message is shown, just the preview is launched.

**Comment by IvanaBlzvc** [comment]
retested with 0.7.8 = OK
