### ISSUE TITLE
Clarify for users that local passwords do not need to be shared 

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#309]

**Comment by IvanaBlzvc** [comment]
Would it be enough to just add another sentence to this window 
![image](https://github.com/equalitie/ouisync-app/assets/121942562/d6783a82-8bb9-49ac-9ee4-e2bd935c047c)
to say for example: this password protects this repository on your device, there is no need to share it.  
The same sentence would need to also be added to this screen
![image](https://github.com/equalitie/ouisync-app/assets/121942562/6313c228-1cbd-48a7-9139-9c1d0877b583)

maybe this one too 
![image](https://github.com/equalitie/ouisync-app/assets/121942562/fb62b372-f20f-4b2c-b9fa-54417ccc8600)

and this one 
![image](https://github.com/equalitie/ouisync-app/assets/121942562/1e1bbcfc-a351-4bd9-a372-89f4f90cb11c)

and this sone 
![image](https://github.com/equalitie/ouisync-app/assets/121942562/8b5aae78-3a95-4dfe-985f-2a472faab018)

**Comment by jnny** [comment]
It might make more sense to users if we call this a *personal* password rather than a local password..

**Comment by IvanaBlzvc** [comment]
Following today's standup, it has been decided that probably the best way to handle this is not to add more text to the dialogue boxes, but to changed them into screens.  
@kermoshina @jnny we'd like you input as to the best text to use that would inform the user that they don't need to share the password from one device to other devices or users... 
We were thinking something like: 
"This password protects this repository on this device.  You don't need to share it with other devices or users."
What do you think?  How could it be improved?

Thanks.

**Comment by inetic** [comment]
> It might make more sense to users if we call this a personal password rather than a local password.. Or better, a "personal passphrase - make it memorable!"

I agree that "personal" _sounds_ better, but I think the semantics is less correct. I think with "personal" there is an implicit implication or encouragement that it should be the same for one repo across all devices belonging to the same person.

**Comment by jnny** [comment]
Makes sense, though in all honesty most people will probably use the same password for all their repos (I certainly need to or I'll forget, but this is also in part because LastPass now charges $$ for using multiple devices and I prefer to use it on my laptop). The disclaimer @IvanaBlzvc wrote sounds good - this could also be included in onboarding screens or tooltips.

**Comment by IvanaBlzvc** [comment]
question in MM for xenia.

**Comment by inetic** [comment]
We are working on a user manual which will clarify this
