### ISSUE TITLE
Better explain the Peer numbers presented in the app settings

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#310]
related to #352 once documented, then the UI will need to display the info for the user (webview, like for FAQ, privacy policy etc?)

**Comment by IvanaBlzvc** [comment]
Today's standup/: this will be done by adding a small (i) button on the Peers screen (where appropriate) and the info bubble will point the user to the user manual that will contain detailed info.  See #352

**Comment by IvanaBlzvc** [comment]
UX input - what would be the best way to display this info from the Peers screen?

**Comment by inetic** [comment]
We now only show the number of connected peers
