### ISSUE TITLE
Privacy policy doesn't open on Android devices

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#346]
Steps to reproduce: 
- Go to app settings and scroll down to About > Privacy policy
- Tap on Privacy policy. 

Expected results: 
- privacy policy github page opens

Actual results: 
- no page opens.  On Desktop it does open this page https://github.com/equalitie/ouisync-app/blob/master/PRIVACY.md

**Comment by J-Pabon** [comment]
@IvanaBlzvc 

The fix is here: cd08a2af1d7018cdab7fb67cebf8f211464491c6

**Comment by IvanaBlzvc** [comment]
Hey, @jorge, please can you change the url to this one: https://ouisync.net/privacy/

then we can close this.

**Comment by J-Pabon** [comment]
> Hey, @J-Pabon please can you change the url to this one: https://ouisync.net/privacy/
> 
> then we can close this.

It is already on master. Can you please re-test it?

Here: edea95378febf942b1aeacaeac93cb1958a026c3

**Comment by IvanaBlzvc** [comment]
retested with 0.7.7 = OK
