### ISSUE TITLE
Folder location displayed incorrectly in folder settings

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#347]
A strange bug... 
This folder structure doesn't seem to be displayed correctly in the folder settings modal window. 
folder123/fff1/ff1/f1 
If I go to settings for folder f1, this is what I see... 
![screenshot-1698406504996](https://github.com/equalitie/ouisync-app/assets/121942562/3dc66e8b-bb4a-4e7f-94ab-d4cd5b64c26d)

**Comment by IvanaBlzvc** [comment]
but if I create the same 4 levels folder structure and I call folders Folder 1, 2, 3 and 4... then the location seems to be displayed correctly 
![screenshot-1698407109788](https://github.com/equalitie/ouisync-app/assets/121942562/350552ff-b45b-4217-b169-576683e0408f)

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix is here: 25e34f6851eb97d7da8a21f34b1bd598c82849b8

**Comment by IvanaBlzvc** [comment]
tested with RC 0.7.5 = OK
