### ISSUE TITLE
Windows: app version seems to always show 1.0.0

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#353]
Steps to reproduce: 
- download the exe file from github, version 0.7.5 and run it. 

Expected results: 
- the app installs correctly and shows the version 0.7.5 in the app settings > about 

Actual results: 
- in the app settings > about, the version shown is 1.0.0
- 
![Screenshot 2023-11-03 105540](https://github.com/equalitie/ouisync-app/assets/121942562/88933c72-df20-4b40-b808-d88024ea2efe)
even though the 0.7.5 is installed 
![Screenshot 2023-11-03 105758](https://github.com/equalitie/ouisync-app/assets/121942562/139b5975-91be-49d9-ad2d-08772bcb993b)

**Comment by IvanaBlzvc** [comment]
retested wit 0.7.7 , still NOK

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix is already on `master` here 23262822d0827c01449f14bda8730710b3fe562a

**Comment by inetic** [comment]
Fixed
