### ISSUE TITLE
Windows app - some modal windows don't take input from keyboard

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#359]
Steps to reproduce 
- in the windows ouisync app got to file > options and select the move option.  (or the same option for a folder)
- The bring the focus onto the blue plus button to add a  folder (which will become a destination folder)
- A dialog box opens
- 
![Screenshot 2023-11-09 122407](https://github.com/equalitie/ouisync-app/assets/121942562/bd5e53de-3dae-43d0-8e3a-7b7f749e81cc)

Expected results: 
- it should be possible to bring focus on one of these two buttons using the tab key and perform its functions using the Enter key
Actual results
- the dialog box doesn't seem to tak einput from any key on the kayboard

**Comment by IvanaBlzvc** [comment]
still the same - retested with 0.7.8

**Comment by inetic** [comment]
We'll create separate tickets per each screen where this is an issue
