### ISSUE TITLE
Unable to create repository on iPad

### ISSUE THREAD

**Issue by jnny** [equalitie/ouisync-app#363]
This is via Apple App Store:

> We discovered one or more bugs in your app. Specifically, we were unable to enter a name to create a new repository. Please review the details below and complete the next steps. 
> Review device details:
> Device type: iPad
> OS version: iOS 17.1 
>  App Version: 0.7.5 for iOS

**Comment by IvanaBlzvc** [comment]
@jnny this is now fixed.  Can you please retest on your ipad and close the ticket if all OK?  Thanks.

**Comment by IvanaBlzvc** [comment]
confirmed fixed.
