### ISSUE TITLE
Spelling mistake in a toast message

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#369]
![Screenshot from 2023-11-23 12-17-31](https://github.com/equalitie/ouisync-app/assets/121942562/cc656c0a-a650-4179-9b15-f6600f312ff9)
higher.. Not higger.

I tried to share a repo with read permission.  I clicked on the (disabled) Write button here ... and then saw the above toast message 
![Screenshot from 2023-11-23 12-20-42](https://github.com/equalitie/ouisync-app/assets/121942562/06a3ccbb-cfb9-4c49-9721-b441c70b1aaa)

**Comment by J-Pabon** [comment]
Fixed here: 85af034730e37f5d7dcc54b04f57085ab1f645b4
