### ISSUE TITLE
[Android] Save file to device fails with error: Cannot open file

### ISSUE THREAD

**Issue by J-Pabon** [equalitie/ouisync-app#371]
Issue: 
Saving (downloading) a file from Ouisync to the `Downloads` folder on Android fails due to a permission denied error.

Environment:

-  Android 10

Steps: 

- Tap the vertical menu on a file item.
- Select `Download`.
- The default location is `Downloads` folder
- Tap the `...` icon to open the folder picker.
- Tap on button: `ALLOW ACCESS TO "DOWNLOADS"`.
- Tap on `ALLOW`.
- Tap on `SAVE`

Expected: 

- File is saved (download) to the `Downloads` folder.

Result:

- There is an exception: `Download file /12Llp8x.jpg exception PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/12Llp8x.jpg' (OS Error: Permission denied, errno = 13)`

- Exception: 

```
D/flutter-ouisync( 5339):  DEBUG Download file /12Llp8x.jpg exception PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/12Llp8x.jpg' (OS Error: Permission denied, errno = 13)
D/flutter-ouisync( 5339): #0      _checkForErrorResponse (dart:io/common.dart:55:9)
D/flutter-ouisync( 5339): #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
D/flutter-ouisync( 5339): #2      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
D/flutter-ouisync( 5339): #3      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
D/flutter-ouisync( 5339): #4      Future._completeWithValue (dart:async/future_impl.dart:647:5)
D/flutter-ouisync( 5339): #5      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
D/flutter-ouisync( 5339): #6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
D/flutter-ouisync( 5339): #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Attachments:

![image](https://github.com/equalitie/ouisync-app/assets/13749449/885aa8b9-4838-42e6-a292-f508d15f81ef)

***

![image](https://github.com/equalitie/ouisync-app/assets/13749449/4829e74e-d666-4db9-b7f2-1ff7da15b555)

***

![image](https://github.com/equalitie/ouisync-app/assets/13749449/41440c57-3dbe-4de0-8538-3e115db54fdf)

**Comment by J-Pabon** [comment]
It seems to work as expected on Android 14, with some differences in how it works:

![image](https://github.com/equalitie/ouisync-app/assets/13749449/b111ef48-91a1-457d-94a4-17419da36005)

![image](https://github.com/equalitie/ouisync-app/assets/13749449/3b51af27-b2a5-4c4f-9eb0-b407ad8a3434)

![image](https://github.com/equalitie/ouisync-app/assets/13749449/6972e443-5c00-4b1f-8b33-8c240cac706d)

![image](https://github.com/equalitie/ouisync-app/assets/13749449/ab96269a-5a49-4a03-8bab-7ef965554fb9)

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

Can you please test this on your Android devices, and desktop.

The commit: 26798d991d640a8c0767b7e7acab451045e21395

Thanks!

**Comment by IvanaBlzvc** [comment]
Retested with 0.7.7 - there are still some issues here, but the download does happen.  To prevent this ticket becoming a meandering one, I will close it and report other small problems separately

**Comment by IvanaBlzvc** [comment]
Closing
