### ISSUE TITLE
Desktop apps - unable to download a file from the ouisync app to the device

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#378]
This seems to have been in issue introduced during the work on Android permissions related to downloading files onto user's device. 

Tested on Windows using 0.7.7 and LInux 0.7.6 

- this indicates that it may have been introduced before 0.7.6?
- 
- .

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

This was a stupid mistake on my side. It should be fixed on the latest master, here:  ed36c8258bcf0fee7d8374d83020844a269edb7e

**Comment by IvanaBlzvc** [comment]
Tested with RC  0.7.8 on Windows... = OK
