### ISSUE TITLE
Delete a repo dialog box - change the options to Delete and Cancel

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#382]
When the user wants to delete a repository, they get a dialog box that offers them two options: Delete and Close.  Whereas when the user wants to delete a file or folder, the options they get are Delete and Cancel.  

For consistency's sake, please correct the 'delete and close' to 'delete and cancel' when deleting a repo.

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 
 
 The fix is already on ` master`, here 49c3df8b873a3deb46d17cca57354307a84027ba

**Comment by IvanaBlzvc** [comment]
OK, can be merged.  To retest with next RC.

**Comment by IvanaBlzvc** [comment]
retested with 080 20240418 = OK
