### ISSUE TITLE
[Bug] Copied files and created files sometime created fail.

### ISSUE THREAD

**Issue by fbewivpjsbsby** [equalitie/ouisync-app#388]
### Version, approach of installation, operating system

1. What version of ouisync are you using?
v0.7.7
2. What approach of installation do you install ouisync?
github release exe.
3. What is your operating system?
Windows 10

### Description
Copying and creating files failed when the created file name contained two Chinese or Japanese characters plus a period and three English characters.

### Steps to reproduce
1. Start ouisync and create a repository.
2. Create a file and rename to 复制.txt or コピー.txt from non-ouisync mounted drive.
3. Copy these files to the ouisync repository. It show error 0X8007054F: An internal error occurred.

### Logs：

 ```bash
ERROR panic at lib\src\conflict.rs:21:9 :: create_entry{create_directory=false delete_access=true}:async_create_file{file_name=Ok("\\コピー.txt")} :: bridge\src\logger\mod.rs:166
ERROR panic at lib\src\conflict.rs:21:9 :: create_entry{create_directory=false delete_access=true}:async_create_file{file_name=Ok("\\コピー.txt")} :: bridge\src\logger\mod.rs:166
ERROR panic at lib\src\conflict.rs:21:9 :: create_entry{create_directory=false delete_access=true}:async_create_file{file_name=Ok("\\コピー.txt")} :: bridge\src\logger\mod.rs:166
 ```

**Comment by IvanaBlzvc** [comment]
Hi @fbewivpjsbsby 
We are trying to reproduce the errors you had and need to understand better the steps to reproduce. 
- Create a repository is clear. 
- but where do you create a file?  on C drive?  ie on your computer's hard drive in a folder on the main C drive?  
- then what did you do after that?  rename that file in the same folder where it has been created? 
- then copy that file and paste where exactly?
- you cannot paste a file directly onto the ouisync O drive (see screenshot)
- 
![Screenshot 2024-01-03 125947](https://github.com/equalitie/ouisync-app/assets/121942562/097fc1db-d8bf-491f-a50c-33ecaf0f5217)
But files can be pasted into one of the repositories... like this ...
![Screenshot 2024-01-03 130152](https://github.com/equalitie/ouisync-app/assets/121942562/258ba787-bb62-4437-a66d-10654c792fdd)

Can are you able to paste the same file into one of the repostiories on your O drive - without using any special Chinese characters? 
- 
- are you able to send us the file you used?

**Comment by fbewivpjsbsby** [comment]
> Hi @fbewivpjsbsby We are trying to reproduce the errors you had and need to understand better the steps to reproduce.
> 
>     * Create a repository is clear.
> 
>     * but where do you create a file?  on C drive?  ie on your computer's hard drive in a folder on the main C drive?
> 
>     * then what did you do after that?  rename that file in the same folder where it has been created?
> 
>     * then copy that file and paste where exactly?
> 
>     * you cannot paste a file directly onto the ouisync O drive (see screenshot)
> 
> 
> ![Screenshot 2024-01-03 125947](https://private-user-images.githubusercontent.com/121942562/293907539-097fc1db-d8bf-491f-a50c-33ecaf0f5217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDUwMjIsIm5iZiI6MTcwNDU0NDcyMiwicGF0aCI6Ii8xMjE5NDI1NjIvMjkzOTA3NTM5LTA5N2ZjMWRiLWQ4YmYtNDkxZi1hNTBjLTMzZWNhZjBmNTIxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjM4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjhkYWQ3YWE3ZmYzMGY5YjgxMzI3OWI0NWE4NGJmZDRjNjhjNTQzZDNiYzI4NjhhZTI5MTRlMzJkMGY3MGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y9lfaLbqWALKKuJyacX47XW2vArY2sjVEPK-d2vRbZI) But files can be pasted into one of the repositories... like this ... ![Screenshot 2024-01-03 130152](https://private-user-images.githubusercontent.com/121942562/293907849-258ba787-bb62-4437-a66d-10654c792fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDUwMjIsIm5iZiI6MTcwNDU0NDcyMiwicGF0aCI6Ii8xMjE5NDI1NjIvMjkzOTA3ODQ5LTI1OGJhNzg3LWJiNjItNDQzNy1hNjZkLTEwNjU0Yzc5MmZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMjM4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTZkNDI4ZTg1ZGZmY2JkNzQzZDlhMDU1YTVjYmU4YzY4MmZlZjQ3NTE5YmZlOGMxNWFiMTNhYjZjZGQ2ZDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EnqQo_ZX0r8ZnEhfbQyuUwKDCqG54iOl82quFLHJedA)
> 
> Are you able to paste the same file into one of the repostiories on your O drive - without using any special Chinese characters?
> 
>     * are you able to send us the file you used?

1. Create the file on any drive other than the drive where ouisync is mounted, such as C: or D:, but not O: (ouisync).
2. Create a file using the new, text file, and rename it to Copy.txt or コピー.txt in the created folder.
3. If we create the file C:\复制.txt then copy or move this file to O:\[repo name]\复制.txt.
4. Yes, I copy this file in O:\[repo name].
5. Yes, I can copy files with only English letters name.
6. Just blank file name 复制.txt, you can use ```type NUL > 复制.txt``` creat it.

If you need Windows command line, change [repo name] to your ouisync repo name
```dos
C:
type NUL > 复制.txt
copy 复制.txt O:\[repo name]
```
It say.
```dos
An internal error occurred.
    0 file(s) copied.
```

**Comment by inetic** [comment]
@fbewivpjsbsby thank you for reporting this, I could reproduce the issue and it should now be fixed (in commit https://github.com/equalitie/ouisync/commit/a59c71a78660589ced20dc281c2e404e848a6a81). The fix will be included in the next Ouisync release.

**Comment by IvanaBlzvc** [comment]
re-tested with RC 0.7.8 20230117 = OK
@fbewivpjsbsby we will publish this release in a day or two - when available, please re-test and let us know if you have any further issues.

**Comment by fbewivpjsbsby** [comment]
> re-tested with RC 0.7.8 20230117 = OK @fbewivpjsbsby we will publish this release in a day or two - when available, please re-test and let us know if you have any further issues.

lgtm.

### Logs:
Creat file
```
ERROR error=STATUS_NOT_IMPLEMENTED :: async_set_file_attributes{file_name=Ok("\\复制.txt")} :: vfs\src\dokan\mod.rs:662
```
Delete file
```
DEBUG unreachable blocks removed: 1 :: job{trash id=60}:repo{C:\Users\[User name]\Documents/ouisync\[repo].db} :: lib\src\repository\worker.rs:667
ERROR error=EntryNotFound :: create_entry{create_directory=false delete_access=false}:async_create_file{file_name=Ok("\\复制.txt")} :: vfs\src\dokan\mod.rs:176
ERROR error=EntryNotFound :: async_create_file{file_name=Ok("\\复制.txt")} :: vfs\src\dokan\mod.rs:313
ERROR error=EntryNotFound :: create_entry{create_directory=false delete_access=false}:async_create_file{file_name=Ok("\\复制.txt")} :: vfs\src\dokan\mod.rs:176
ERROR error=EntryNotFound :: async_create_file{file_name=Ok("\\复制.txt")} :: vfs\src\dokan\mod.rs:3132024-01-18T02:10:14.423120Z DEBUG Sync progress: 32768/32768 bytes (100.0%) :: repo{C:\Users\[User name]\Documents/ouisync\[repo].db} :: lib\src\repository\mod.rs:930
```
