### ISSUE TITLE
Weblink referred twice but has no content

### ISSUE THREAD

**Issue by Ser-Bul** [equalitie/ouisync-app#390]
The FAQ both in [Wiki](https://github.com/equalitie/ouisync-app/wiki/Frequently-Asked-Questions) at GitHub and the Website's code at Weblate (Website JSON, key faqContent24[English]) refer to the "What is a 'local password'?" weblink https://github.com/equalitie/ouisync-app/wiki/_new#what-is-a-local-password
But that link is broken (no content there).
Please fix the link (add content) or update the Wiki and Website's code.

**Comment by jnny** [comment]
Thanks for the catch, @Ser-Bul ! I have updated both links :)
