### ISSUE TITLE
Windows, Linux - after file download, toast message prevents the Move

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#393]
Tested with 0.7.8

Steps to reproduce

- Create a repo, add a few files and create a couple of folders within the same repo
- Perform a few file downloads from a ouisync repository, into the file system on device. 
- After each download there is a toast message confirming that the download was successful and giving the user location where the file was downloaded to.  The file can be seen in that location on device.
- After that, select a file that is in the repo root, and try to move it to a folder within that same repo

Expected results
- file can be moved to the folder
Actual results 
- when the user tries to move the file, the toast message that confirms the download pops up and the Move button is disabled.  
![Screenshot from 2024-01-23 10-39-01](https://github.com/equalitie/ouisync-app/assets/121942562/3dff8b2b-85e9-455b-8dd4-bded65ae1e41)

**Comment by IvanaBlzvc** [comment]
From the MM conversation on 22 Jan.  

"This one seems like an issue with the mechanism to prevent the same toast to be displayed more than once; I think I remember there is a cubit taking care of that"

**Comment by IvanaBlzvc** [comment]
On Android, the same toast message popups up when I try to do move after download... (but I can dismiss it and continue with the move... )

**Comment by J-Pabon** [comment]
Hi @IvanaBlzvc 

The fix for this issue is on this branch: [fix-issue-393](https://github.com/equalitie/ouisync-app/tree/fix-issue-393)

**Comment by IvanaBlzvc** [comment]
retested with 080 20240418 = OK
