### ISSUE TITLE
Load the repository .db files from a non-standard location (USB stick etc)

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#397]
There is a need for ouisync to be able to load repository .db files from a storage device, such as USB stick or similar.  This is different from importing the repository.  When importing - the app will import the whole repo and place it in a predefined location, where all the other repos, that are already present on device, reside. 

When loading, though, the ouisync will be able to access and share the contents of repository from its current location - ie from the USB stick.  

"One point about sharing the ouisync db into ousync (not very relevant for Leah, but still wanted to bring it up): I think we should use a custom file extension for the db (in the CLI app we use .ouisyncdb, so we should probably stick with that) and then register Ouisync as a handler for files with this extension. Then when the user taps on the ouisync database in the file browser, they won't get the generic share sheet. Instead they will be offered to open the file directly with Ousiync. (there would also be an option to use a different app, but Ouisync will be the default). " (MM, 1st feb 2024, QA channel)

There is a small UX component to this as the user will need to be able to access those .db files from the ouisync UI.

**Comment by inetic** [comment]
Implemented in version 0.8.0
