### ISSUE TITLE
Android 14 - After restarting the app, repos with no password won't unlock

### ISSUE THREAD

**Issue by J-Pabon** [equalitie/ouisync-app#401]
Tested with version ouisync_0.7.8-20240207101917.1fbf56c7.apk

Steps to reproduce:

- Install APK and create a repository without adding a password.

- Lock the repo, thjen unlock it from the button UNLOCK = OK

- Close the app (swipe from the open apps stack).

- Open the app, and select the same repo.

- Tap on UNLOCK button

Results:

- The repo unlock fails; a toast with the message "The password did not unlock the repository" is shown.
![Screenshot_20240207-224747](https://github.com/equalitie/ouisync-app/assets/13749449/ba3df8ad-3eee-4238-99ad-684495dbc52f)

Expected results: 

- Everytime the button UNLOCK is tapped for a repo without password, it should unlock the repo and display a toast indicating the access mode.

**Comment by IvanaBlzvc** [comment]
rested with 080 20240416 = OK
