### ISSUE TITLE
File preview doesn't work and sometimes crashes the whole device

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#402]
In the [latest master](https://github.com/equalitie/ouisync-app/commit/b0997a91fc98d3cddcf0cb52c93227c0f2ff5637), previewing a file doesn't work. Depending on the device/os version it either shows just blank screen or even crashes the device (causing restart). 

Possible culprit is the introduction of the [android_alarm_manager_plus](https://pub.dev/packages/android_alarm_manager_plus) plugin to run the background sync. Quick experiments show that commenting out its [initialization code](https://github.com/equalitie/ouisync-app/blob/master/lib/main.dart#L17) makes the preview work again. Further investigation is needed.

**Comment by IvanaBlzvc** [comment]
retested with version ouisync_0.7.8-20240208125854.64a6dc78 = OK
