### ISSUE TITLE
Inconsistent margins

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#58]
I think the one for folders (red) doesn't need fixing, that is, the fact that the file size information is missing is probably OK(?). Though I think the margin below the file size should be the same as the one above the file name.

![Screenshot_20220221-110511](https://user-images.githubusercontent.com/40127/154934894-24f1461f-437b-4da8-99d9-6bce18bbb2d9.jpg)

**Comment by inetic** [comment]
Reopening as the margins still seem off
![margins](https://user-images.githubusercontent.com/40127/156337933-17581ffb-2eca-4a64-8eb7-bf57cb3efcb8.jpg)

**Comment by inetic** [comment]
I may be wrong, but do you not have some kind of invisible widget below the file size widget? I think if it really was the case that the margin is the same above the file name and below the file size, then the space above file name should actually look bigger due to letters having different sizes. But it's the other way around.

Also note the margin difference of the top widget.

**Comment by J-Pabon** [comment]
No, I don't have an invisible widget there. So I need to check why that is still happening.

I am adding there the progress bar, and when not needed, an empty `SizedBox` with `height=0`, so that should not affect that when added.

About the margin in the `AppBar`: noted.

**Comment by IvanaBlzvc** [comment]
fixed.
