### ISSUE TITLE
Can't switch folder while a file is being uploaded from the phone into ouisync

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#82]
Steps to reproduce:

1. Create a folder `/foo`
2. While in root, press the (+) button and upload a large file into `/`
3. While the file is being uploaded, try to enter the `/foo` folder

The step number 3 will not succeed until the file is fully uploaded.

**Comment by IvanaBlzvc** [comment]
I retested this with build 57119efa
I am able to switch between folders before the upload is finished, and I can also switch from one repo to another.  
However, while retesting this, I have found anothe issue  - when the user tries to upload several files in the row, on windows app, the app becomes unresponsive.  Reported a ticket #209 for that.
Closing this ticket.
