### ISSUE TITLE
Find a way to change the log tag

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#88]
Currently the log tag of messages printed from the flutter/dart side use hardcoded tag "flutter" which makes it hard to filter only the messages coming from ouisync and not any other app that also happens to be written in flutter.

**Comment by J-Pabon** [comment]
What tag should we used for the app?

![image](https://user-images.githubusercontent.com/13749449/158759276-62d93e19-3604-43b0-b206-165899cefb97.png)

I can customize it pretty much however we want. The example above is using the tag `OuiSync App` and it includes the class name from where it was logged.

**Comment by madadam** [comment]
Looks good. Maybe use just "ouisync - CLASS_NAME" as the tag?

**Comment by J-Pabon** [comment]
Resolved here 33a091a9d13d931ac895a7492eabf4e4511f38b2
