### ISSUE TITLE
Sharing into ouisync requires unlocking the repo even when already unlocked

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#90]
Steps to reproduce:
1. Open ouisync and unlock a repo
2. Switch to a different app, e.g. the file browser
3. Pick a file and share it
4. Pick ouisync as the app to share it with
5. Ouisync will ask to unlock the repository even though we already unlocked it in step 1

We should probably not ask to unlock it again in this case. However, if the user want's to share the file into a different repo than the one currently opened, asking them to unlock it first is the correct thing to do.

**Comment by inetic** [comment]
I think the relevant term to look for is ["task affinity"](https://stackoverflow.com/a/17873524/273348)

**Comment by inetic** [comment]
Should be fixed by 9bfaec1
